### ISSUE TITLE
Enclosure option (Stevenson screen)

### ISSUE THREAD

**Issue by colinmccormick** [GeorgetownMakerHubOrg/air-quality#1]
Here's a 3D-printable enclosure for weather station electronics - seems like it would be useful for us.

https://www.thingiverse.com/thing:2282869

**Comment by fpgirard** [comment]
Cool - let’s add that.     Reduces cost.    
  

  
The silver spring library will 3D print stuff very cheaply.     Takes about a week or so.   
  

  
  

  
  
>

**Comment by fpgirard** [comment]
Okay, this is basically what I did….   Great validation!

On August 20, 2018 at 1:34:00 PM, Colin McCormick (notifications@github.com) wrote:

Here's a 3D-printable enclosure for weather station electronics - seems like it would be useful for us.

https://www.thingiverse.com/thing:2282869

**Comment by theFestest** [comment]
If we intend to be mainly pushing the Acurite enclosures, this thread may be ready to close.

**Comment by fpgirard** [comment]
Who wants to contact Acurite and ask for $?

F. Pascal Girard
+1.301.633.7673
fpg13@georgetown.edu
pascal.girard@jhu.edu


On July 11, 2019 at 12:14:31 PM, Michael Bartholic (notifications@github.com) wrote:

If we intend to be mainly pushing the Acurite enclosures, this thread may be ready to close.
