### ISSUE TITLE
Enter deep sleep if battery level reaches critical threshold

### ISSUE THREAD

**Issue by theFestest** [GeorgetownMakerHubOrg/air-quality#14]
From the readme:

> On a battery monitor when the lithium battery hits a certain threshold, enter deep sleep to prevent total depletion.

With the imminent use of battery-powered monitors, there will be a need to sleep the monitor before fully depleting the battery. It may also be a good idea to build in the capability of notifying on critical battery, so the user can go and replace/recharge the battery.

**Comment by fpgirard** [comment]
You can monitor amperage on the ESP.  You can then set web hooks to IFTTT to alert to status.    Again, we’re publishing great ideas to everyone.

If you want to see an ESP on a battery, look here.  You can actually see the voltage plummet on June 19th after running for 60 or so days.  Michael - this is a unit you saw in my living room….

As for managing power usage by sensors, I’d be inclined to include on the shield a MOSFET design that shuts off power to the sensors but is enabled with the ESP wakes. That way, we don’t have to handle the nuances of each sensor sleep wake implementation.

The biggest issue for battery is the 5v required to run the fans in the PM sensors.  It’s the only component on GUAQ that requires 5v.   Why can’t they run on 3.3v????

P




On July 12, 2019 at 10:31:26 AM, Michael Bartholic (notifications@github.com) wrote:

From the readme:

On a battery monitor when the lithium battery hits a certain threshold, enter deep sleep to prevent total depletion.

With the imminent use of battery-powered monitors, there will be a need to sleep the monitor before fully depleting the battery. It may also be a good idea to build in the capability of notifying on critical battery, so the user can go and replace/recharge the battery.
