### ISSUE TITLE
Contributing, code of conduct, and PR templates

### ISSUE THREAD

**Issue by theFestest** [GeorgetownMakerHubOrg/air-quality#19]
Putting together these files and templates will go far to enable consistent community expectations and quality work.

See [this](https://github.com/GeorgetownMakerHubOrg/air-quality/issues/7#issuecomment-509318438) and the linked project for examples of the direction I'm thinking. I'm planning on working on this myself in the coming days.

**Comment by cmpadden** [comment]
@michaelbartholic , I modified the `README` in _contributing-guidelines_ to include a logo I created for the GUAQ project. In hindsight I should have created my own branch; In the future I'll make my own, sorry about that!

**Comment by theFestest** [comment]
Hey sweet @cmpadden! It's no problem. For minor things and small bugs I don't mind commits to the same working branch too much, but thanks for the mindfulness of that bc it can definitely get messy with rectifying big changes and conflicts. 

Viewing the `README.md` from the home page has it show up as a broken image for me (weird?), but I was able to check it out and it rendered properly by putting the link in my browser. I like it. 

We actually put together the first try at a logo a couple of weeks ago too which we used when presenting. It's much wider and more horizontal than yours (I really appreciate how it could fit in square or circular profile picture) so I can envision both being useful.

**Comment by cmpadden** [comment]
I wasn't aware of the previous logo, whoops! 

As for the link not working, that is because it references the file being hosted on the `master` branch. Once the code is merged it should work fine. 

> air-quality/blob/`master`/static/GUAQ-150px.png

I'm not aware of a way to host static files in a GitHub repository that works on multiple branches.

**Comment by theFestest** [comment]
Oh it’s totally cool. I’m glad you put this one together because I’ve been thinking about needing a more compact/square variant. I’ll show you the other one sometime soon, and make sure to put the assets for it somewhere if you wanted to experiment with that too.

**Comment by cmpadden** [comment]
What is the status of this issue?

Are we almost ready to merge the `contributing-guidelines` branch?

**Comment by theFestest** [comment]
@cmpadden Yep, #29 ready to merge whenever you like. I had a grander vision for those files at one point but I feel this is sufficient for now. I'm happy with it.
