### ISSUE TITLE
upgrade upload to call esptool and upgrade script

### ISSUE THREAD

**Issue by fpgirard** [GeorgetownMakerHubOrg/air-quality#24]
I'm going to suggest that we have 2 bash scripts in the /bin directory:

1. upload - which calls esptool to erase and reflash the esp and then calls upgrade
2. upgrade - calls ampy and uploads all the guaq files.  Upgrade takes  /dev/tty... as an argument.

This will allow us to minimally disrupt our field sites by requiring that they install ampy only.  Until we can get the WebREPL tested and documented better.

Pas

**Comment by cmpadden** [comment]
Something that I'm also curious about, that we should look into, is if we can include a distribution of _ampy_ in the repository. I've seen other projects do this for small utilities.

**Comment by fpgirard** [comment]
For upload.py, change the --device argument to --port.  This will make it consistent with most serial port utilities (like ampy and esptool) that used --port.   Easy fix

**Comment by cmpadden** [comment]
> For upload.py, change the --device argument to --port. This will make it consistent with most serial port utilities (like ampy and esptool) that used --port. Easy fix

Completed in #33.
