### ISSUE TITLE
bme280 implementation needs a fix.

### ISSUE THREAD

**Issue by fpgirard** [GeorgetownMakerHubOrg/air-quality#36]
**Describe the bug**
BME280 implementation appears broken.  How did we miss this?
lib/bme280/__init__.py is empty when it should provide the BME280 class.
line 16 in tph.py should read "from lib import bme280" not "from lib.bme280 import bme280".

**To Reproduce**
1. Configure wake.py to support only tph.py
2. upload the code.
3. get the error "Running Sensors...
Traceback (most recent call last):
  File "main.py", line 25, in run
  File "wake.py", line 24, in main
  File "sensors/tph.py", line 16, in <module>
ImportError: no module named 'lib.bme280.bme280'

**Comment by cmpadden** [comment]
It looks like the `bme280.py` library was missing, as it was included in the `.gitignore` file. I've removed that entry, and checked it in to version control. Let me know if this works for you.

**Comment by cmpadden** [comment]
See #37.

**Comment by fpgirard** [comment]
Fixed - and merged.
