### ISSUE TITLE
Transition to release tagging, development branch, and semantic version

### ISSUE THREAD

**Issue by theFestest** [GeorgetownMakerHubOrg/air-quality#7]
As currently stands, all PRs and changes are merged directly into master and we don't use semantic versioning to keep track of releases.

Before any significant work continues (besides hotfixes), I recommend that we transition to a system of merging PRs into a "development" branch and then merging "development" into master after some level of formalized testing. 

Additionally, I feel that would be beneficial to tag our current "release" software as some beta tag (v0.2.1?) and implement semantic versioning to keep track of who/what units have what software version to better debug and manage our distribution.

This will enable us to increase the rate of development without risking releasing untested code. Of course hotfixes, for example, could be merged otherwise and development branches could be deployed onto monitors, but in general, this will help our stability and sustainability.

**Comment by cmpadden** [comment]
That is a good idea.

Would it make sense to add a file, `CONTRIBUTING.md`, to outline the branching and versioning conventions?

**Comment by theFestest** [comment]
Sure. I think that's a good option. Perhaps we could make a reference to it in the `README.md` so it appears on the main page as well.

**Comment by theFestest** [comment]
To the same end, a PR template would be a wise addition as this project grows.

**Comment by cmpadden** [comment]
I find that the Postgraphile project is a good example of how to structure markdown files. In addition to a `CONTRIBUTING.md` file, they also have a `CHANGELOG.md` file.

https://github.com/graphile/postgraphile
