### ISSUE TITLE
Robust nonsequencial serial number generation and assignment for monitors

### ISSUE THREAD

**Issue by theFestest** [GeorgetownMakerHubOrg/air-quality#9]
In order to scale we are going to want to maintain a database of all devices and be able to generate serials as new ones are added to the GUAQ network. In addition to letting us count and advertise the number of active devices, this will let us more easily increase the security of our data collection down the line. 

Perhaps there's a way to generate this with a hash function pulling hardware information from the chips and then checking to ensure it doesn't collide with an existing device?

**Comment by cmpadden** [comment]
We may have to combine this with something additional, but the `machine` class has a `unique_id` method that:

> Returns a string of 6 bytes (48 bits), which is the unique ID of the MCU. This also corresponds to the network `MAC address`.

**Comment by fpgirard** [comment]
I’m totally confused by this thread - if MAC addresses are assured to be unique, why wouldn’t we key off of that?  Effectively, this should be the serial number and we could always create a QR code, print it, and place on the mount.

iot.py, I believe, uses this id to post to the proper group under my account.   

P


On July 11, 2019 at 2:09:35 PM, Colton (notifications@github.com) wrote:

We may have to combine this with something additional, but the machine class has a unique_id method that:

Returns a string of 6 bytes (48 bits), which is the unique ID of the MCU. This also corresponds to the network MAC address.

**Comment by theFestest** [comment]
> if MAC addresses are assured to be unique

While this is a fair assumption in many contexts, at large scales with possibly varying hardware sources and user intentions, I don't believe this should be our assumption going forward. 

Of course, we don't have a well-developed threat model yet, but it should be noted that MAC addresses are _supposed to be unique_ but this is **not** assured. These can be spoofed relatively easily but also there have been instances where manufacturers simply cheap out and assign multiple devices the same ID. One consideration is that we should plan for cases where someone is trying to post fraudulent data to the data board without even interacting with the device. With something like a MAC address, this could as easy as running the command manually.

Otherwise, its generally not good practice to use MAC addresses as an ID on a public network or as any means of authentication/identification. For more details on why it's not universally okay to assume MACs are unique, see [this](https://superuser.com/questions/1258721/reasons-not-to-assume-device-mac-address-is-unique).

I was envisioning this "serial" being used as somewhat of an account ID for a given device that can be used when posting data to the data board, but also as a means of keeping track of how many devices we have out and functioning. For both of these instances, we need to be as absolutely sure as we can that no two devices can have the same ID/serial at the same time. This could be further useful in that we could develop functionality that allows a new device to inherit the history of an existing device if it is being replaced: in this instance, the ID/serial could be used to identify a node's history and then the new device could inherit the history by reassociating the ID and having the history release the old one.

Perhaps the values to identify a device by serial and identify a device's history as separate from a device should be separate? I really don't know, but in either event, I don't feel that a raw MAC address is sufficient. Ideally, there would be some way to identify and verify that a device is a genuine one and better yet (while not directly related to this thread) genuinely in/near the location it claims to be as a means of security. 

I believe maintaining a database of properly guaranteed-unique serial numbers of nodes on the GUAQ network is an important factor in these goals. 

> we could always create a QR code, print it, and place on the mount.

This is a cool idea actually, and making some easy way of retrieving the code when having the device physically present is an added bit of "security" while still keeping it easy to use.
